// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mariadb.Data;

#nullable disable

namespace mariadb.Migrations
{
    [DbContext(typeof(AutoparkDbContext))]
    [Migration("20250711115426_NovaMigracija")]
    partial class NovaMigracija
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("mariadb.Entities.Automobil", b =>
                {
                    b.Property<int>("IdAutomobila")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAutomobila"));

                    b.Property<DateTime>("DatumRegistracije")
                        .HasColumnType("date");

                    b.Property<bool>("Dostupan")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("GodinaProizvodnje")
                        .HasColumnType("int");

                    b.Property<int>("IdGoriva")
                        .HasColumnType("int");

                    b.Property<int>("IdProizvodjac")
                        .HasColumnType("int");

                    b.Property<decimal>("KilometriNaRegistraciji")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("Potrosnja")
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("Registracija")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("ccm")
                        .HasColumnType("int");

                    b.Property<int?>("kW")
                        .HasColumnType("int");

                    b.HasKey("IdAutomobila");

                    b.HasIndex("IdGoriva");

                    b.HasIndex("IdProizvodjac");

                    b.ToTable("Automobili");
                });

            modelBuilder.Entity("mariadb.Entities.Gorivo", b =>
                {
                    b.Property<int>("IdGoriva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdGoriva"));

                    b.Property<decimal>("CijenaGoriva")
                        .HasColumnType("decimal(5,1)");

                    b.Property<string>("NazivGoriva")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdGoriva");

                    b.ToTable("Goriva");
                });

            modelBuilder.Entity("mariadb.Entities.Korisnik", b =>
                {
                    b.Property<int>("IdKorisnika")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdKorisnika"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImePrezime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("JeAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdKorisnika");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("mariadb.Entities.PravnaOsoba", b =>
                {
                    b.Property<int>("IdPravnaOsoba")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPravnaOsoba"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Mjesto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("IdPravnaOsoba");

                    b.ToTable("PravnaOsoba");
                });

            modelBuilder.Entity("mariadb.Entities.Proizvodjac", b =>
                {
                    b.Property<int>("IdProizvodjac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProizvodjac"));

                    b.Property<string>("NazivProizvodjaca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdProizvodjac");

                    b.ToTable("Proizvodjaci");
                });

            modelBuilder.Entity("mariadb.Entities.Rezervacija", b =>
                {
                    b.Property<int>("IdRezervacije")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRezervacije"));

                    b.Property<DateTime>("DatumDolaska")
                        .HasColumnType("date");

                    b.Property<DateTime>("DatumOdlaska")
                        .HasColumnType("date");

                    b.Property<int>("IdAutomobila")
                        .HasColumnType("int");

                    b.Property<int>("IdKorisnika")
                        .HasColumnType("int");

                    b.Property<string>("Mjesto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Odobreno")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RazlogOpis")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Udaljenost")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("IdRezervacije");

                    b.HasIndex("IdAutomobila");

                    b.HasIndex("IdKorisnika");

                    b.ToTable("Rezervacije");
                });

            modelBuilder.Entity("mariadb.Entities.Servis", b =>
                {
                    b.Property<int>("IdServisa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdServisa"));

                    b.Property<decimal>("CijenaServisa")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("DatumServisa")
                        .HasColumnType("date");

                    b.Property<int>("IdAutomobila")
                        .HasColumnType("int");

                    b.Property<string>("OpisServisa")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("IdServisa");

                    b.HasIndex("IdAutomobila");

                    b.ToTable("Servisi");
                });

            modelBuilder.Entity("mariadb.Entities.Automobil", b =>
                {
                    b.HasOne("mariadb.Entities.Gorivo", "Gorivo")
                        .WithMany("Automobili")
                        .HasForeignKey("IdGoriva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mariadb.Entities.Proizvodjac", "Proizvodjac")
                        .WithMany("Automobili")
                        .HasForeignKey("IdProizvodjac")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gorivo");

                    b.Navigation("Proizvodjac");
                });

            modelBuilder.Entity("mariadb.Entities.Rezervacija", b =>
                {
                    b.HasOne("mariadb.Entities.Automobil", "Automobil")
                        .WithMany("Rezervacije")
                        .HasForeignKey("IdAutomobila")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mariadb.Entities.Korisnik", "Korisnik")
                        .WithMany("Rezervacije")
                        .HasForeignKey("IdKorisnika")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Automobil");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("mariadb.Entities.Servis", b =>
                {
                    b.HasOne("mariadb.Entities.Automobil", "Automobil")
                        .WithMany("Servisi")
                        .HasForeignKey("IdAutomobila")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Automobil");
                });

            modelBuilder.Entity("mariadb.Entities.Automobil", b =>
                {
                    b.Navigation("Rezervacije");

                    b.Navigation("Servisi");
                });

            modelBuilder.Entity("mariadb.Entities.Gorivo", b =>
                {
                    b.Navigation("Automobili");
                });

            modelBuilder.Entity("mariadb.Entities.Korisnik", b =>
                {
                    b.Navigation("Rezervacije");
                });

            modelBuilder.Entity("mariadb.Entities.Proizvodjac", b =>
                {
                    b.Navigation("Automobili");
                });
#pragma warning restore 612, 618
        }
    }
}
